version: '3'
services:
  django:
    build: ./02_movies_admin
    volumes:
      - data:/opt/app/static/     
    depends_on:
      - db
    expose:
      - "8000" 
    env_file:
      - ./02_movies_admin/config/.env

  db:
    image: postgres:13
    volumes:
      - /home/nikita/postgresql/data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./02_movies_admin/config/.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - data:/data/:ro
    depends_on:
      - django
    ports:
      - "80:80"

volumes:
    data:
